In [42]:
import numpy as np
import cv2

In [44]:
#face detection

In [46]:
img=cv2.imread('./images/modi.jpeg')
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [48]:
#load casecade classifier- frontface

In [50]:
face_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_frontalface_default.xml')

In [52]:
#apply cascadeclassifier to an image

In [54]:
faces,num_detection=face_cascade.detectMultiScale2(img)

In [56]:
print(faces)

[[78 42 69 69]]


In [58]:
print(num_detection)

[15]


In [60]:
s1=(78,42)
s2=(78+69,42+69)
#draw the rectangle
cv2.rectangle(img,s1,s2,(0,255,0))
cv2.imshow('face detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [62]:
#draw the circle
cx= 78+ 69//2
cy= 42+ 69//2
r=  69//2
cv2.circle(img, (cx, cy), r, (0, 255, 255), 2)
cv2.imshow('face detection circle',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


MULTIFACE DETECTION

In [65]:
img=cv2.imread('./images/multi.jpg')
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [67]:
face_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_frontalface_default.xml')

In [105]:
faces,num_detection=face_cascade.detectMultiScale2(img,minNeighbors=12)
#step-1
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
#step-2 display images
cv2.imshow('face detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
    

In [98]:
print(faces)

[[407 383  74  74]
 [252 338  89  89]
 [533 342  97  97]]


In [101]:
print(num_detection)

[53 32 88]
