In [1]:
import numpy as np
import cv2

In [3]:
#face detection

In [5]:
img=cv2.imread('./images/modi.jpeg')
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
#load casecade classifier- frontface

In [9]:
face_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_frontalface_default.xml')

In [11]:
#apply cascadeclassifier to an image

In [13]:
faces,num_detection=face_cascade.detectMultiScale2(img)

In [14]:
print(faces)

[[78 42 69 69]]


In [17]:
print(num_detection)

[15]


In [19]:
s1=(78,42)
s2=(78+69,42+69)
#draw the rectangle
cv2.rectangle(img,s1,s2,(0,255,0))
cv2.imshow('face detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
#draw the circle
cx= 78+ 69//2
cy= 42+ 69//2
r=  69//2
cv2.circle(img, (cx, cy), r, (0, 255, 255), 2)
cv2.imshow('face detection circle',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


MULTIFACE DETECTION

In [24]:
img=cv2.imread('./images/multi.jpg')
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
face_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_frontalface_default.xml')

In [28]:
faces,num_detection=face_cascade.detectMultiScale2(img,minNeighbors=12)
#step-1
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
#step-2 display images
cv2.imshow('face detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
    

In [30]:
print(faces)

[[407 383  74  74]
 [252 338  89  89]
 [533 342  97  97]]


In [32]:
print(num_detection)

[53 32 88]


FACES & EYES DETECTION

In [35]:
img=cv2.imread('./images/multi.jpg')
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [37]:
face_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_eye.xml')

In [46]:
#step-1 FaceDtections
faces,num_detection=face_cascade.detectMultiScale2(img,minNeighbors=8)
for x,y,w,h in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
    face_roi=img[y:y+h,x:x+h]
    eyes,num_detection_eyes=eye_cascade.detectMultiScale2(face_roi)
    for ex,ey,ew,eh  in eyes:
        cx=x+ex+ew//2
        cy=y+ey+eh//2
        r=eh//2
        cv2.circle(img,(cx,cy),r,(255,0,255),2)

cv2.imshow('face eye detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()


Face Eyes AND smile Detection

In [49]:
img=cv2.imread('./images/multi.jpg')
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
face_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_frontalface_default.xml')
eye_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_eye.xml')
smile_cascade=cv2.CascadeClassifier('cascade_classifier/haarcascade_smile.xml')
#step-1 FaceDtections
faces,num_detection=face_cascade.detectMultiScale2(img,minNeighbors=8)
for x,y,w,h in faces:
    face_roi=img[y:y+h,x:x+h].copy()
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0))
    
    eyes,num_detection_eyes=eye_cascade.detectMultiScale2(face_roi)
    for ex,ey,ew,eh  in eyes:
        cx=x+ex+ew//2
        cy=y+ey+eh//2
        r=eh//2
        cv2.circle(img,(cx,cy),r,(255,0,255),2)
    smaile,num_detection_smaile=smile_cascade.detectMultiScale2(face_roi)
    for sx,sy,sw,sh in smaile:
        cv2.rectangle(img,(x+sx,y+sy),(x+sx+sw,y+sy+sh),(255,0,0),2)
    


cv2.imshow('face eye detection',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
